default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: housing_api_development
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

test:
  <<: *default
  database: housing_api_test

production:
  cable:
    <<: *default
    database: <%= ENV.fetch("DATABASE_URL") %>
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>