default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: housing_api_development
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

test:
  <<: *default
  database: housing_api_test

production:
  primary: &primary_production
    <<: *default
    database: housing_api_production
    username: <%= ENV.fetch("DB_USERNAME") %>
    password: <%= ENV.fetch("DB_PASSWORD") %>
  cache:
    <<: *primary_production
    database: housing_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: housing_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: housing_api_production_cable
    migrations_paths: db/cable_migrate
    
